### ISSUE TITLE
Is this implementation reference on this paper? 

### ISSUE THREAD

**Issue by xxlylf** [stefaanja/Basic_Bitwise_Operator_Neural_Network#1]
Is this implementation reference on this paper?
http://120.52.73.80/arxiv.org/pdf/1601.06071v1.pdf

**Comment by stefaanja** [comment]
@xxlylf From what I can tell after reading it, no it is not. This system is very rudimentary and was only created when I was first learning how to implement Neural Nets. The tutorial I followed for this is even included in the README. Could you be a little more clear as to what you are asking?
